'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5485
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System.Runtime.Serialization

Namespace Sevansoft.CacheTest.Entities
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Product", [Namespace]:="http://schemas.datacontract.org/2004/07/Sevansoft.CacheTest.Entities")>  _
    Partial Public Class Product
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject
        
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private CodeField As String
        
        Private DateField As Date
        
        Private NameField As String
        
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Code() As String
            Get
                Return Me.CodeField
            End Get
            Set
                Me.CodeField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property [Date]() As Date
            Get
                Return Me.DateField
            End Get
            Set
                Me.DateField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Name() As String
            Get
                Return Me.NameField
            End Get
            Set
                Me.NameField = value
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="ProductList", [Namespace]:="http://schemas.datacontract.org/2004/07/Sevansoft.CacheTest.Entities", ItemName:="Product")>  _
    Public Class ProductList
        Inherits System.Collections.Generic.List(Of Sevansoft.CacheTest.Entities.Product)
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="CountryInfoList", [Namespace]:="http://schemas.datacontract.org/2004/07/Sevansoft.CacheTest.Entities", ItemName:="CountryInfo")>  _
    Public Class CountryInfoList
        Inherits System.Collections.Generic.List(Of Sevansoft.CacheTest.Entities.CountryInfo)
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="CountryInfo", [Namespace]:="http://schemas.datacontract.org/2004/07/Sevansoft.CacheTest.Entities")>  _
    Partial Public Class CountryInfo
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject
        
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private CodeField As String
        
        Private DateField As Date
        
        Private NameField As String
        
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Code() As String
            Get
                Return Me.CodeField
            End Get
            Set
                Me.CodeField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property [Date]() As Date
            Get
                Return Me.DateField
            End Get
            Set
                Me.DateField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Name() As String
            Get
                Return Me.NameField
            End Get
            Set
                Me.NameField = value
            End Set
        End Property
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="StateInfoList", [Namespace]:="http://schemas.datacontract.org/2004/07/Sevansoft.CacheTest.Entities", ItemName:="StateInfo")>  _
    Public Class StateInfoList
        Inherits System.Collections.Generic.List(Of Sevansoft.CacheTest.Entities.StateInfo)
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="StateInfo", [Namespace]:="http://schemas.datacontract.org/2004/07/Sevansoft.CacheTest.Entities")>  _
    Partial Public Class StateInfo
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject
        
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private CodeField As String
        
        Private NameField As String
        
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Code() As String
            Get
                Return Me.CodeField
            End Get
            Set
                Me.CodeField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Name() As String
            Get
                Return Me.NameField
            End Get
            Set
                Me.NameField = value
            End Set
        End Property
    End Class
End Namespace


<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
 System.ServiceModel.ServiceContractAttribute(ConfigurationName:="IProduct")>  _
Public Interface IProduct
    
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServiceBase/ClearCache", ReplyAction:="http://tempuri.org/IServiceBase/ClearCacheResponse")>  _
    Sub ClearCache()
    
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IProduct/GetProduct", ReplyAction:="http://tempuri.org/IProduct/GetProductResponse")>  _
    Function GetProduct(ByVal code As String) As Sevansoft.CacheTest.Entities.Product
    
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IProduct/GetProducts", ReplyAction:="http://tempuri.org/IProduct/GetProductsResponse")>  _
    Function GetProducts() As Sevansoft.CacheTest.Entities.ProductList
End Interface

<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
Public Interface IProductChannel
    Inherits IProduct, System.ServiceModel.IClientChannel
End Interface

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
Partial Public Class ProductClient
    Inherits System.ServiceModel.ClientBase(Of IProduct)
    Implements IProduct
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal endpointConfigurationName As String)
        MyBase.New(endpointConfigurationName)
    End Sub
    
    Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
        MyBase.New(endpointConfigurationName, remoteAddress)
    End Sub
    
    Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
        MyBase.New(endpointConfigurationName, remoteAddress)
    End Sub
    
    Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
        MyBase.New(binding, remoteAddress)
    End Sub
    
    Public Sub ClearCache() Implements IProduct.ClearCache
        MyBase.Channel.ClearCache
    End Sub
    
    Public Function GetProduct(ByVal code As String) As Sevansoft.CacheTest.Entities.Product Implements IProduct.GetProduct
        Return MyBase.Channel.GetProduct(code)
    End Function
    
    Public Function GetProducts() As Sevansoft.CacheTest.Entities.ProductList Implements IProduct.GetProducts
        Return MyBase.Channel.GetProducts
    End Function
End Class

<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
 System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ICountryInformation")>  _
Public Interface ICountryInformation
    
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IServiceBase/ClearCache", ReplyAction:="http://tempuri.org/IServiceBase/ClearCacheResponse")>  _
    Sub ClearCache()
    
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICountryInformation/GetCountryInfos", ReplyAction:="http://tempuri.org/ICountryInformation/GetCountryInfosResponse")>  _
    Function GetCountryInfos() As Sevansoft.CacheTest.Entities.CountryInfoList
    
    <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ICountryInformation/GetStateInfos", ReplyAction:="http://tempuri.org/ICountryInformation/GetStateInfosResponse")>  _
    Function GetStateInfos(ByVal countryCode As String) As Sevansoft.CacheTest.Entities.StateInfoList
End Interface

<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
Public Interface ICountryInformationChannel
    Inherits ICountryInformation, System.ServiceModel.IClientChannel
End Interface

<System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
Partial Public Class CountryInformationClient
    Inherits System.ServiceModel.ClientBase(Of ICountryInformation)
    Implements ICountryInformation
    
    Public Sub New()
        MyBase.New
    End Sub
    
    Public Sub New(ByVal endpointConfigurationName As String)
        MyBase.New(endpointConfigurationName)
    End Sub
    
    Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
        MyBase.New(endpointConfigurationName, remoteAddress)
    End Sub
    
    Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
        MyBase.New(endpointConfigurationName, remoteAddress)
    End Sub
    
    Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
        MyBase.New(binding, remoteAddress)
    End Sub
    
    Public Sub ClearCache() Implements ICountryInformation.ClearCache
        MyBase.Channel.ClearCache
    End Sub
    
    Public Function GetCountryInfos() As Sevansoft.CacheTest.Entities.CountryInfoList Implements ICountryInformation.GetCountryInfos
        Return MyBase.Channel.GetCountryInfos
    End Function
    
    Public Function GetStateInfos(ByVal countryCode As String) As Sevansoft.CacheTest.Entities.StateInfoList Implements ICountryInformation.GetStateInfos
        Return MyBase.Channel.GetStateInfos(countryCode)
    End Function
End Class
