'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3607
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Reflection
<Assembly: AssemblyVersionAttribute("0.0.0.0"), _
 Assembly: AssemblyFileVersionAttribute("0.0.0.0"), _
 Assembly: AssemblyCompanyAttribute("CDS Global"), _
 Assembly: AssemblyCopyrightAttribute("Copyright © CDS Global 2015"), _
 Assembly: AssemblyConfigurationAttribute("DEBUG"), _
 Assembly: AssemblyInformationalVersionAttribute("0.0")> 