'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace Sevansoft.CacheTest.ServiceTier.Azure
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Product", [Namespace]:="http://schemas.datacontract.org/2004/07/Sevansoft.CacheTest.Entities"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Product
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NameField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Code() As String
            Get
                Return Me.CodeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodeField, value) <> true) Then
                    Me.CodeField = value
                    Me.RaisePropertyChanged("Code")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Name() As String
            Get
                Return Me.NameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NameField, value) <> true) Then
                    Me.NameField = value
                    Me.RaisePropertyChanged("Name")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.CollectionDataContractAttribute(Name:="ProductList", [Namespace]:="http://schemas.datacontract.org/2004/07/Sevansoft.CacheTest.Entities", ItemName:="Product"),  _
     System.SerializableAttribute()>  _
    Public Class ProductList
        Inherits System.Collections.Generic.List(Of Sevansoft.CacheTest.ServiceTier.Azure.Product)
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="Sevansoft.CacheTest.ServiceTier.Azure.IProduct")>  _
    Public Interface IProduct
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IProduct/ClearCache", ReplyAction:="http://tempuri.org/IProduct/ClearCacheResponse")>  _
        Sub ClearCache()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IProduct/ClearCache", ReplyAction:="http://tempuri.org/IProduct/ClearCacheResponse")>  _
        Function ClearCacheAsync() As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IProduct/GetProduct", ReplyAction:="http://tempuri.org/IProduct/GetProductResponse")>  _
        Function GetProduct(ByVal code As String) As Sevansoft.CacheTest.ServiceTier.Azure.Product
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IProduct/GetProduct", ReplyAction:="http://tempuri.org/IProduct/GetProductResponse")>  _
        Function GetProductAsync(ByVal code As String) As System.Threading.Tasks.Task(Of Sevansoft.CacheTest.ServiceTier.Azure.Product)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IProduct/GetProducts", ReplyAction:="http://tempuri.org/IProduct/GetProductsResponse")>  _
        Function GetProducts() As Sevansoft.CacheTest.ServiceTier.Azure.ProductList
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IProduct/GetProducts", ReplyAction:="http://tempuri.org/IProduct/GetProductsResponse")>  _
        Function GetProductsAsync() As System.Threading.Tasks.Task(Of Sevansoft.CacheTest.ServiceTier.Azure.ProductList)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IProductChannel
        Inherits Sevansoft.CacheTest.ServiceTier.Azure.IProduct, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ProductClient
        Inherits System.ServiceModel.ClientBase(Of Sevansoft.CacheTest.ServiceTier.Azure.IProduct)
        Implements Sevansoft.CacheTest.ServiceTier.Azure.IProduct
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Sub ClearCache() Implements Sevansoft.CacheTest.ServiceTier.Azure.IProduct.ClearCache
            MyBase.Channel.ClearCache
        End Sub
        
        Public Function ClearCacheAsync() As System.Threading.Tasks.Task Implements Sevansoft.CacheTest.ServiceTier.Azure.IProduct.ClearCacheAsync
            Return MyBase.Channel.ClearCacheAsync
        End Function
        
        Public Function GetProduct(ByVal code As String) As Sevansoft.CacheTest.ServiceTier.Azure.Product Implements Sevansoft.CacheTest.ServiceTier.Azure.IProduct.GetProduct
            Return MyBase.Channel.GetProduct(code)
        End Function
        
        Public Function GetProductAsync(ByVal code As String) As System.Threading.Tasks.Task(Of Sevansoft.CacheTest.ServiceTier.Azure.Product) Implements Sevansoft.CacheTest.ServiceTier.Azure.IProduct.GetProductAsync
            Return MyBase.Channel.GetProductAsync(code)
        End Function
        
        Public Function GetProducts() As Sevansoft.CacheTest.ServiceTier.Azure.ProductList Implements Sevansoft.CacheTest.ServiceTier.Azure.IProduct.GetProducts
            Return MyBase.Channel.GetProducts
        End Function
        
        Public Function GetProductsAsync() As System.Threading.Tasks.Task(Of Sevansoft.CacheTest.ServiceTier.Azure.ProductList) Implements Sevansoft.CacheTest.ServiceTier.Azure.IProduct.GetProductsAsync
            Return MyBase.Channel.GetProductsAsync
        End Function
    End Class
End Namespace
